<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="35258" started-at="2019-09-13T01:25:28Z" finished-at="2019-09-13T01:26:03Z">
    <groups>
    </groups>
    <test name="treiner Test" duration-ms="35258" started-at="2019-09-13T01:25:28Z" finished-at="2019-09-13T01:26:03Z">
      <class name="co.treiner.testCases.TC_HomePage">
        <test-method status="PASS" signature="setup(java.lang.String)[pri:0, instance:co.treiner.testCases.TC_HomePage@1a3869f4]" name="setup" is-config="true" duration-ms="11579" started-at="2019-09-13T01:25:28Z" finished-at="2019-09-13T01:25:40Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="navigationTest()[pri:0, instance:co.treiner.testCases.TC_HomePage@1a3869f4]" name="navigationTest" duration-ms="21885" started-at="2019-09-13T01:25:40Z" finished-at="2019-09-13T01:26:02Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at co.treiner.testCases.TC_HomePage.navigationTest(TC_HomePage.java:41)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- navigationTest -->
        <test-method status="PASS" signature="end()[pri:0, instance:co.treiner.testCases.TC_HomePage@1a3869f4]" name="end" is-config="true" duration-ms="619" started-at="2019-09-13T01:26:03Z" finished-at="2019-09-13T01:26:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- end -->
      </class> <!-- co.treiner.testCases.TC_HomePage -->
    </test> <!-- treiner Test -->
  </suite> <!-- Suite -->
</testng-results>
